### ISSUE TITLE
Elevation Cloud does not allow for multi-level mapping

### ISSUE THREAD

**Issue by pkeefeEndeavor** [TixiaoShan/traversability_mapping#4]
When I map an area with multiple levels that cross over each other, the "elevation_pointcloud" becomes distorted and localization is lost.  Is there a parameter for tuning the "level height" or am I looking at the wrong output? 

In this video, you show multiple levels being mapped and traversed:

https://www.youtube.com/watch?time_continue=159&v=bQt2OMlQ8tY&feature=emb_logo

How do I reproduce these results?

**Comment by TixiaoShan** [comment]
@pkeefeEndeavor 
Sorry for the late reply. I have deleted the multi-level mapping function as there are too many parameters involved and buggy. So the current package only works for single-level mapping.

**Comment by pkeefeEndeavor** [comment]
@TixiaoShan is it possible to get the multi-level mapping function on a branch so that we could try it out and help make updates to it?  I'm very interested in this functionality and I would be curious to understand the bugs.  I would hate to see such a great feature disappear.

**Comment by TixiaoShan** [comment]
[traversability_mapping.zip](https://github.com/TixiaoShan/traversability_mapping/files/4231145/traversability_mapping.zip)

Here is my backup for that version in 2017. To enable multi-level mapping, I basically stack a vector of "vector of cells" in the sub-map (see the utility.h). To extract the level the robot is on, I use the breadth-first search to start with the cell the robot is on and search all the cells that satisfy some threshold (publishLocalOccupancyGridMap() in traversability_map.cpp).

Since this is a very old package, I am not even sure I can compile it anymore.

**Comment by TixiaoShan** [comment]
@pkeefeEndeavor

**Comment by pkeefeEndeavor** [comment]
@TixiaoShan Thank you so much, I can't wait to check it out!

**Comment by rock19970106** [comment]
Hi, @pkeefeEndeavor , have you solved this problem?
