### ISSUE TITLE
Code problem and save prm graph

### ISSUE THREAD

**Issue by Yeah2333** [TixiaoShan/traversability_mapping#7]
@TixiaoShan ，Hi,these days i have finish map save and load code,using my custom msgs to save mapArray in bag file.So,i have some question about traversability_mapping.
1.I want to save prm graph ,i check the code , prm graph seems like save in
 ` vector<state_t*> nodeList;
    vector<state_t*> pathList;`,i need save and load these vector?
2.prm node sub a topic named /occupancy_map_local_height,in my load code ,pub this topic works good,but it cant generate prm graph,that means i must save the prm_graph vector? 

3.I have find a node named traversability_path ,but in your launch ,you dont use this node.Could you tell me about this node meaning?
Thank you very much.
![tra](https://user-images.githubusercontent.com/22851247/78977354-907b0880-7b4a-11ea-99e1-91b538f8905c.png)

**Comment by TixiaoShan** [comment]
@Yeah2333 
1. Yes, all the PRM nodes are saved in that vector.
2. The PRM code needs this ```occupancy_map_local_height``` to update its node and edge in the local region. So if you want to save all the info and load it for new planning, you need to save the vector.
3. This file is another planner. It's using pre-computed paths. Here is a video of it. Because I stopped working on this project, so this planner has some issues when used. https://youtu.be/Wrs_m1KCT2g

**Comment by Yeah2333** [comment]
@TixiaoShan Sorry fo reply late，i found i have explore the code,and i have some question.
1.`vector<state_t*> nodeList`is save the rpm node and edge info,`vector<state_t*> pathList`is save the path that generate by planner.That means if i want to save prm data,i just save nodeList.Is right?

2.The function of prm.cpp.`generateSamples()` `updateStatesAndEdges()`is use for update prm data,`bfsSearch()` is use for planner,is right?

3. If right,that means some data in `struct state_t` just use in planner.Also ,in `struct state_t` ,i have find `vector<state_t*> childList; // RRT*`i cant find using in prm.cpp,just find it in path.cpp . And `    float costsToParent[NUM_COSTS]; // used in RRT*
    float costsToGo[NUM_COSTS];` I cant find where use these data, both in path.cpp and prm.cpp.

From your code，i learn many things about c++ and roscpp,thank you very much.

**Comment by TixiaoShan** [comment]
> @TixiaoShan Sorry fo reply late，i found i have explore the code,and i have some question.
> 1.`vector<state_t*> nodeList`is save the rpm node and edge info,`vector<state_t*> pathList`is save the path that generate by planner.That means if i want to save prm data,i just save nodeList.Is right?
> 
> 2.The function of prm.cpp.`generateSamples()` `updateStatesAndEdges()`is use for update prm data,`bfsSearch()` is use for planner,is right?
> 
> 1. If right,that means some data in `struct state_t` just use in planner.Also ,in `struct state_t` ,i have find `vector<state_t*> childList; // RRT*`i cant find using in prm.cpp,just find it in path.cpp . And `    float costsToParent[NUM_COSTS]; // used in RRT* float costsToGo[NUM_COSTS];` I cant find where use these data, both in path.cpp and prm.cpp.
> 
> From your code，i learn many things about c++ and roscpp,thank you very much.

@Yeah2333 
1. Yes
2. Yes
3. Those variables were used in an RRT* planner that I have stopped using because generating a tree each time is quite expensive. You can just ignore or delete those unused variables.

**Comment by Yeah2333** [comment]
@TixiaoShan Thank you very much ,i have finish my code ,and test planning ,it work. Next ,i will review my code,and add location module. Another question , how to make legoloam's result cloud more dense? Do you need these code?I be willing to email these code to you.

**Comment by TixiaoShan** [comment]
@Yeah2333 
That's excellent news!
To increase the density of lego-loam's cloud, you can decrease the [params of voxel grid filter](https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/blob/57476bc7c41ef9775030a90801eb6de750b1f573/LeGO-LOAM/src/mapOptmization.cpp#L249). Keep in mind that decrease these params will increase the computation burden.
I'd love to use your code. Thanks for willing to share it!

**Comment by Yeah2333** [comment]
@TixiaoShan Hi,
1.i have change params of voxel grid filter .but it seem like some error `[pcl::VoxelGrid::applyFilter] Leaf size is too small for the input dataset. Integer indices would overflow.`
2.I still in check my code,what's your email you use?  Is `tixiao.shan@gmail.com` ?After check and finish doc,i wiil email to you.
3.About lego loam,can Lego loam load pointcloud and location using previous map. If need i add my own code,it is easy or difficult?

**Comment by TixiaoShan** [comment]
@Yeah2333 
1. That's a warning when the leaf size is too small. If you want the visualized global point cloud becomes denser, you can comment out [this line here](https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/blob/aa37d0a9553f94ec5c59755cf5fb0a15f84a53f4/LeGO-LOAM/src/mapOptmization.cpp#L787). Basically, you publish "globalMapKeyFrames" directly instead of down-sampled it to "globalMapKeyFramesDS".
2. That's my email. 
3. I consider it's easier to reload the map for lego-loam. The important information is all saved in mapOptimization.cpp (the vector of feature point clouds there). About the GTSAM factor graph, I am not sure how to save it. But since if you are using it for localization, the factor graph can probably be deleted. Basically it will become the new incoming scans to a global point cloud map. This global point cloud map is fused from those vector of feature point clouds.

**Comment by Yeah2333** [comment]
@TixiaoShan  I have email my code to you .Mail named Code of Traversability mapping.My email address is wangzhiyong@cuhk.edu.cn .And the using step i have write in readme.md. Thank you for your help about answer so many question. Also,if it have some bugs, please tell me.

**Comment by TixiaoShan** [comment]
@Yeah2333 
Thank you so much for sharing your code!

**Comment by rock19970106** [comment]
@Yeah2333 , Hi, could you share the code to me ? My email is : zhlupeng@mail.ustc.edu.cn. Thank you very much!

**Comment by bimalka98** [comment]
Hi @Yeah2333, 
I am currently working on developing a Field Robot with Autonomous Navigation as my final year project in my B. Sc. of Eng. degree program. 

I found the conversation between you and the author of this repo really helpful, and you have solved exactly the same problem that I am struggling with at the moment (saving the traversability map, and planning the path using the saved map). 

I would be really grateful if you could share your code with me at 180631j@uom.lk or bimalkapiyaruwan1998322@gmail.com. The former address is the one associated with my university (University of Moratuwa, Sri Lanka, APAC), and the latter is my personal email. Thank you for your time, and looking forward to hearing from you. (I was not sure whether your email is still the same as mentioned in the above conversation and thought of contacting you through a comment.)

**Comment by Yeah2333** [comment]
Hi, @bimalka98 The bad news is that I've been so busy writing my master's thesis lately that I'm afraid I won't have time to put together the code and then send it to you because my previous email address isn't working and I can't find the email with the author. The good news is that I plan to start reorganizing this work next week and then release it publicly. Of course, this will include a map-based localization section and contain very specific documentation on replication. traversability_mapping is very serious work, especially for beginners, and is an excellent resource for getting started with roscpp and robots. Of course, if you are in a hurry, you can email me to push me next week. I'll put together a simpler version for you first.

**Comment by bimalka98** [comment]
Thank you very much for your prompt reply @Yeah2333. That's totally understandable, because I am asking for your code for almost after three years since you closed this issue. 
**It's absolutely a pleasure to hear that you are planning to release your work publicly because the whole internet lacks that type of work. I have been surfing the internet for about 2-3 weeks and this was the only promising open-source solution I could find which aids autonomous field robot navigation.**
If you can share your current email address with me, I will definitely send you a follow-up reminder regarding this. Thank you again for your time and effort. I really appreciate it.

**Comment by Yeah2333** [comment]
@bimalka98 My personal email is 653091941@qq.com.

**Comment by bimalka98** [comment]
Hi @Yeah2333 I sent you an email reminding my request. Could you please confirm whether you have received that? It may have been directed to your spam folder since my email (bimalkapiyaruwan1998322@gmail.com) is not familiar to your 653091941@qq.com email account. The subject of the email is "Regrading Traversability Mapping ROS package of Tixiao Shan on GitHub".

**Comment by bimalka98** [comment]
Function for saving the PRM graph after the pilot run:    void savePRMGraph()
Function for loading it in subsequent autonomous navigation sessions:  void loadPRMGraph()
[Source code](https://github.com/bimalka98/Traversability-Mapping/blob/master/traversability_mapping/src/traversability_prm.cpp); Tested with an actual robot: [See the demo](https://www.linkedin.com/posts/bimalka98_autonomousvehicles-ugv-mobilerobots-activity-7098502042712776704-DxyF)
